//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPMobileNet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPMobileNet.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration X.
        /// </summary>
        public static string StatusAccelerationX {
            get {
                return ResourceManager.GetString("StatusAccelerationX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration Y.
        /// </summary>
        public static string StatusAccelerationY {
            get {
                return ResourceManager.GetString("StatusAccelerationY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration Z.
        /// </summary>
        public static string StatusAccelerationZ {
            get {
                return ResourceManager.GetString("StatusAccelerationZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        public static string StatusAccuracy {
            get {
                return ResourceManager.GetString("StatusAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        public static string StatusAltitude {
            get {
                return ResourceManager.GetString("StatusAltitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude Accuracy.
        /// </summary>
        public static string StatusAltitudeAccuracy {
            get {
                return ResourceManager.GetString("StatusAltitudeAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string StatusCity {
            get {
                return ResourceManager.GetString("StatusCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string StatusCountry {
            get {
                return ResourceManager.GetString("StatusCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string StatusDevice {
            get {
                return ResourceManager.GetString("StatusDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device battery, hardware, frimware and other kind of properties..
        /// </summary>
        public static string StatusDeviceDescription {
            get {
                return ResourceManager.GetString("StatusDeviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware version.
        /// </summary>
        public static string StatusDeviceFirmwareVersion {
            get {
                return ResourceManager.GetString("StatusDeviceFirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware version.
        /// </summary>
        public static string StatusDeviceHardwareVersion {
            get {
                return ResourceManager.GetString("StatusDeviceHardwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID.
        /// </summary>
        public static string StatusDeviceID {
            get {
                return ResourceManager.GetString("StatusDeviceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Location.
        /// </summary>
        public static string StatusDeviceLocation {
            get {
                return ResourceManager.GetString("StatusDeviceLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Location information from GPS sensor..
        /// </summary>
        public static string StatusDeviceLocationDescription {
            get {
                return ResourceManager.GetString("StatusDeviceLocationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string StatusDeviceManufacturer {
            get {
                return ResourceManager.GetString("StatusDeviceManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string StatusDeviceName {
            get {
                return ResourceManager.GetString("StatusDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading.
        /// </summary>
        public static string StatusHeading {
            get {
                return ResourceManager.GetString("StatusHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Dilution Of Precision.
        /// </summary>
        public static string StatusHorizontalDilutionOfPrecision {
            get {
                return ResourceManager.GetString("StatusHorizontalDilutionOfPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface Name.
        /// </summary>
        public static string StatusInterfaceName {
            get {
                return ResourceManager.GetString("StatusInterfaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface State.
        /// </summary>
        public static string StatusInterfaceState {
            get {
                return ResourceManager.GetString("StatusInterfaceState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface Subtype.
        /// </summary>
        public static string StatusInterfaceSubtype {
            get {
                return ResourceManager.GetString("StatusInterfaceSubtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface Type.
        /// </summary>
        public static string StatusInterfaceType {
            get {
                return ResourceManager.GetString("StatusInterfaceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is plugged in.
        /// </summary>
        public static string StatusIsPluggedIn {
            get {
                return ResourceManager.GetString("StatusIsPluggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is power saving mode enabled.
        /// </summary>
        public static string StatusIsPowerSavingModeEnabled {
            get {
                return ResourceManager.GetString("StatusIsPowerSavingModeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string StatusLatitude {
            get {
                return ResourceManager.GetString("StatusLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationOrigin.
        /// </summary>
        public static string StatusLocationOrigin {
            get {
                return ResourceManager.GetString("StatusLocationOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string StatusLongitude {
            get {
                return ResourceManager.GetString("StatusLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Data Technology.
        /// </summary>
        public static string StatusMobileDataTechnology {
            get {
                return ResourceManager.GetString("StatusMobileDataTechnology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Operator.
        /// </summary>
        public static string StatusMobileOperator {
            get {
                return ResourceManager.GetString("StatusMobileOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile operator connection details..
        /// </summary>
        public static string StatusMobileOperatorDescription {
            get {
                return ResourceManager.GetString("StatusMobileOperatorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedometer status.
        /// </summary>
        public static string StatusPedometerStatus {
            get {
                return ResourceManager.GetString("StatusPedometerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping.
        /// </summary>
        public static string StatusPing {
            get {
                return ResourceManager.GetString("StatusPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Ping to Google (8.8.8.8). The delay time is in milliseconds..
        /// </summary>
        public static string StatusPingDescription {
            get {
                return ResourceManager.GetString("StatusPingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Dilution Of Precision.
        /// </summary>
        public static string StatusPositionDilutionOfPrecision {
            get {
                return ResourceManager.GetString("StatusPositionDilutionOfPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Source.
        /// </summary>
        public static string StatusPositionSource {
            get {
                return ResourceManager.GetString("StatusPositionSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string StatusPostalCode {
            get {
                return ResourceManager.GetString("StatusPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher Host Id.
        /// </summary>
        public static string StatusPublisherHostId {
            get {
                return ResourceManager.GetString("StatusPublisherHostId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining charge percent.
        /// </summary>
        public static string StatusRemainingChargePercent {
            get {
                return ResourceManager.GetString("StatusRemainingChargePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string StatusSpeed {
            get {
                return ResourceManager.GetString("StatusSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string StatusState {
            get {
                return ResourceManager.GetString("StatusState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steeps.
        /// </summary>
        public static string StatusSteeps {
            get {
                return ResourceManager.GetString("StatusSteeps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Dilution Of Precision.
        /// </summary>
        public static string StatusVerticalDilutionOfPrecision {
            get {
                return ResourceManager.GetString("StatusVerticalDilutionOfPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerometer sensor measure X, Y, and Z axis accelerations in m/s2..
        /// </summary>
        public static string VAccelerometerDescription {
            get {
                return ResourceManager.GetString("VAccelerometerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Status.
        /// </summary>
        public static string VHomeButtonUpdateStatus {
            get {
                return ResourceManager.GetString("VHomeButtonUpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string VHomePivotItemHeader0 {
            get {
                return ResourceManager.GetString("VHomePivotItemHeader0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string VHomePivotItemHeader1 {
            get {
                return ResourceManager.GetString("VHomePivotItemHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string VHomePivotItemHeader2 {
            get {
                return ResourceManager.GetString("VHomePivotItemHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        public static string VHomePivotItemHeader3 {
            get {
                return ResourceManager.GetString("VHomePivotItemHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Net.
        /// </summary>
        public static string VHomePivotTitle {
            get {
                return ResourceManager.GetString("VHomePivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting status.
        /// </summary>
        public static string VHomeProgressIndicatorText {
            get {
                return ResourceManager.GetString("VHomeProgressIndicatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerometer.
        /// </summary>
        public static string VHomeSensorsItemHeader1 {
            get {
                return ResourceManager.GetString("VHomeSensorsItemHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedometer.
        /// </summary>
        public static string VHomeSensorsItemHeader2 {
            get {
                return ResourceManager.GetString("VHomeSensorsItemHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get X, Y, and Z axis accelerations..
        /// </summary>
        public static string VHomeSensorsItemLabel1 {
            get {
                return ResourceManager.GetString("VHomeSensorsItemLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steep counter..
        /// </summary>
        public static string VHomeSensorsItemLabel2 {
            get {
                return ResourceManager.GetString("VHomeSensorsItemLabel2", resourceCulture);
            }
        }
    }
}
