//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPMobileNet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPMobileNet.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string StatusDevice {
            get {
                return ResourceManager.GetString("StatusDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device battery, hardware, frimware and other kind of properties..
        /// </summary>
        public static string StatusDeviceDescription {
            get {
                return ResourceManager.GetString("StatusDeviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware version.
        /// </summary>
        public static string StatusDeviceFirmwareVersion {
            get {
                return ResourceManager.GetString("StatusDeviceFirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware version.
        /// </summary>
        public static string StatusDeviceHardwareVersion {
            get {
                return ResourceManager.GetString("StatusDeviceHardwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string StatusDeviceManufacturer {
            get {
                return ResourceManager.GetString("StatusDeviceManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string StatusDeviceName {
            get {
                return ResourceManager.GetString("StatusDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is plugged in.
        /// </summary>
        public static string StatusIsPluggedIn {
            get {
                return ResourceManager.GetString("StatusIsPluggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Operator.
        /// </summary>
        public static string StatusMobileOperator {
            get {
                return ResourceManager.GetString("StatusMobileOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile operator connection details..
        /// </summary>
        public static string StatusMobileOperatorDescription {
            get {
                return ResourceManager.GetString("StatusMobileOperatorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping.
        /// </summary>
        public static string StatusPing {
            get {
                return ResourceManager.GetString("StatusPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Ping to Google (8.8.8.8). The delay time is in milliseconds..
        /// </summary>
        public static string StatusPingDescription {
            get {
                return ResourceManager.GetString("StatusPingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining charge percent.
        /// </summary>
        public static string StatusRemainingChargePercent {
            get {
                return ResourceManager.GetString("StatusRemainingChargePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Status.
        /// </summary>
        public static string VHomeButtonUpdateStatus {
            get {
                return ResourceManager.GetString("VHomeButtonUpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string VHomePivotItemHeader0 {
            get {
                return ResourceManager.GetString("VHomePivotItemHeader0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string VHomePivotItemHeader1 {
            get {
                return ResourceManager.GetString("VHomePivotItemHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string VHomePivotItemHeader2 {
            get {
                return ResourceManager.GetString("VHomePivotItemHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Net.
        /// </summary>
        public static string VHomePivotTitle {
            get {
                return ResourceManager.GetString("VHomePivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting status.
        /// </summary>
        public static string VHomeProgressIndicatorText {
            get {
                return ResourceManager.GetString("VHomeProgressIndicatorText", resourceCulture);
            }
        }
    }
}
